implement in-db depth first search
medema-group/BiG-SCAPE pull request #159
Opened 2024-05-23 15:31 UTC by adraismawur

This PR replaces the turns-out-is-slow-and-awful in-database breadth-first implementation with a more efficient depth-first search.

This is currently more memory-efficient than an entirely in-memory DFS, but slower by 2-3 orders of magnitude.

2024-05-23 15:32 UTC, adraismawur commented
And I again forgot to check if query mode is still OK. this does not rely on random selection of edges or whatever, so some of the arguments passed to CC generation are different in query mode. still needs to be checked.

2024-05-23 15:33 UTC, adraismawur commented on big_scape/network/DBAdjList.py
> +class DBAdjList(Mapping):
I forgot to add a docstring for this class

2024-06-05 09:03 UTC, nlouwen requested changes
lgtm, two small docstring changes requested

2024-06-05 09:03 UTC, nlouwen commented on big_scape/network/network.py
> -    seed_record: Optional[BGCRecord] = None,
Also remove seed_record docstring

2024-06-05 09:03 UTC, nlouwen commented on big_scape/network/network.py
> -        seed_record (BGCRecord, optional): a seed record to start the connected component from.
keep seed_record docstring

2024-06-05 09:36 UTC, nlouwen approved these changes
lgtm

2024-06-05 09:37 UTC, merged