Implement simple match extend
medema-group/BiG-SCAPE pull request #183
Opened 2024-09-27 12:21 UTC by adraismawur

This implements the simple match extend function, which ignores the idea of mismatching and should be much easier to explain than the legacy extend.

2024-09-27 13:33 UTC, nlouwen requested changes
Overall logic is sound, some indexing discrepancies if I am not mistaken. Also needs a merge from dev to add simple_match to the new EXTEND_STRATEGY enum, so mac can multiprocess

2024-09-27 13:33 UTC, nlouwen commented on big_scape/cli/cli_common_options.py
> +            "the type of domain, occurence or position of the domain. See the documentation for more details.",
Unfortunately, this formatting does not seem to get shown on the cmdline help message

2024-09-27 13:33 UTC, nlouwen commented on big_scape/comparison/extend.py
> +    performing a match/gap extentsion similar to legaxy expansion
```suggestion
    performing a match/gap extension similar to legacy expansion
```

2024-09-27 13:33 UTC, nlouwen commented on big_scape/comparison/extend.py
> +    for i in range(pair.comparable_region.lcs_a_stop + 1, len(a_domains)):
lcs_a_stop governs cds bounds, should be lcs_domain_a_stop.
comparable region stops are exclusive, so remove the +1
```suggestion
    for i in range(pair.comparable_region.lcs_domain_a_stop, len(a_domains)):
```

2024-09-27 13:33 UTC, nlouwen commented on big_scape/comparison/extend.py
> +            pair.comparable_region.domain_a_stop = i
stops should be exclusive, so +1 to both cds and domain stops

2024-09-27 13:33 UTC, nlouwen commented on big_scape/comparison/extend.py
> +    for i in range(pair.comparable_region.lcs_a_start - 1, -1, -1):
```suggestion
    for i in range(pair.comparable_region.lcs_domain_a_start - 1, -1, -1):
```

2024-09-27 13:33 UTC, nlouwen commented on big_scape/comparison/extend.py
> +    for i in range(pair.comparable_region.lcs_b_stop + 1, len(b_domains)):
```suggestion
    for i in range(pair.comparable_region.lcs_domain_b_stop, len(b_domains)):
```

2024-09-27 13:33 UTC, nlouwen commented on big_scape/comparison/extend.py
> +            pair.comparable_region.domain_b_stop = i
add +1's

2024-09-27 13:33 UTC, nlouwen commented on big_scape/comparison/extend.py
> +    for i in range(pair.comparable_region.lcs_b_start - 1, -1, -1):
```suggestion
    for i in range(pair.comparable_region.lcs_domain_b_start - 1, -1, -1):
```

2024-09-27 13:33 UTC, nlouwen commented on test/comparison/test_extend.py
> +            9, 10, 6, 7, 9, 10, 6, 7, False
```suggestion
            9, 11, 6, 8, 9, 11, 6, 8, False
```
exclusive ends

2024-09-27 13:33 UTC, nlouwen commented on test/comparison/test_extend.py
> +            6, 10, 5, 7, 6, 10, 5, 7, False
```suggestion
            6, 11, 5, 8, 6, 11, 5, 8, False
```

2024-09-27 13:33 UTC, nlouwen commented on test/comparison/test_extend.py
> +        )
To include if you want, a test with multidomain cds, I used it to figure out the exclusive end confusions

```suggestion
        )
    def test_expand_simple_match_multi_domain(self):
        """Tests glocal expand with multi domain cdss"""
        # brackets indicate a cds with multiple domains
        #
        # A:        [XX]BX[A BC]DEX XXXX
        # B: XXXXXXXXXX XX A[BC]EDX[XXXX]
        #
        a_cds, b_cds = generate_mock_cds_lists(
            10, 17, [3, 3, 3, 4, 5], [12, 13, 13, 15, 14], False
        )
        a_cds[0].hsps.append(a_cds[0].hsps[0])
        a_cds[1].hsps = [a_cds[3].hsps[1]]
        b_cds[-1].hsps.extend([b_cds[-1].hsps[0]] * 3)

        record_a = generate_mock_region(a_cds)
        record_b = generate_mock_region(b_cds)
        pair = big_scape.comparison.record_pair.RecordPair(record_a, record_b)
        pair.comparable_region = bs_comp.ComparableRegion(
            3, 4, 12, 14, 4, 7, 12, 15, False
        )
        bs_comp.extend.extend_simple_match(pair, 5, -2)
        expected_comparable_region = bs_comp.ComparableRegion(
            1, 6, 12, 16, 2, 9, 12, 17, False
        )

        self.assertEqual(pair.comparable_region, expected_comparable_region)
        self.assertEqual(
            pair.comparable_region.domain_a_start,
            expected_comparable_region.domain_a_start,
        )
        self.assertEqual(
            pair.comparable_region.domain_b_start,
            expected_comparable_region.domain_b_start,
        )
        self.assertEqual(
            pair.comparable_region.domain_a_stop,
            expected_comparable_region.domain_a_stop,
        )
        self.assertEqual(
            pair.comparable_region.domain_b_stop,
            expected_comparable_region.domain_b_stop,
        )
```

2024-09-27 13:47 UTC, nlouwen commented on big_scape/comparison/extend.py
> +    for cds_idx, cds in enumerate(pair.record_a.get_cds()):
```suggestion
    for cds_idx, cds in enumerate(pair.record_a.get_cds_with_domains()):
```
I believe extend should only use cds with domains, later on inflate() will be called

2024-09-27 13:48 UTC, nlouwen commented on big_scape/comparison/extend.py
> +    for cds_idx, cds in enumerate(pair.record_b.get_cds()):
```suggestion
    for cds_idx, cds in enumerate(pair.record_b.get_cds_with_domains()):
```

2024-10-01 08:25 UTC, adraismawur commented
Excellent. As usual, working with the coordinates and the cds/domain distinction is not my strong suit.

2024-10-01 08:38 UTC, nlouwen approved these changes
lgtm!

2024-10-01 13:12 UTC, merged